TEST_USERNAME1: str = "test1"
TEST_PASSWORD1: str = "123456"
TEST_USERNAME2: str = "test2"
TEST_PASSWORD2: str = "123456"

TEST_GAME_ID: int = 1
TEST_USER1_ID: int = 1
TEST_USER2_ID: int = 2
TEST_USER1_SHAPE: str = 'ROCK'
TEST_USER2_SHAPE: str = 'PAPER'
TEST_USER1_RESULT: str = 'LOSE'
TEST_USER2_RESULT: str = 'WIN'
